// Mocks generated by Mockito 5.4.5 from annotations
// in sparkcircuit/test/application/interaction_engine_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i11;
import 'dart:ui' as _i3;

import 'package:flutter/material.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:riverpod/src/internals.dart' as _i2;
import 'package:sparkcircuit/core/services/coordinate_system_service.dart'
    as _i4;
import 'package:sparkcircuit/core/services/pathfinding_service.dart' as _i6;
import 'package:sparkcircuit/core/services/wire_network_service.dart' as _i7;
import 'package:sparkcircuit/presentation/features/game/controllers/canvas_interaction_controller.dart'
    as _i12;
import 'package:sparkcircuit/presentation/features/game/services/viewport_service.dart'
    as _i5;
import 'package:state_notifier/state_notifier.dart' as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeProviderContainer_0 extends _i1.SmartFake
    implements _i2.ProviderContainer {
  _FakeProviderContainer_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeKeepAliveLink_1 extends _i1.SmartFake implements _i2.KeepAliveLink {
  _FakeKeepAliveLink_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProviderSubscription_2<State1> extends _i1.SmartFake
    implements _i2.ProviderSubscription<State1> {
  _FakeProviderSubscription_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeOffset_3 extends _i1.SmartFake implements _i3.Offset {
  _FakeOffset_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCoordinateValidationResult_4 extends _i1.SmartFake
    implements _i4.CoordinateValidationResult {
  _FakeCoordinateValidationResult_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeViewportState_5 extends _i1.SmartFake implements _i5.ViewportState {
  _FakeViewportState_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRect_6 extends _i1.SmartFake implements _i3.Rect {
  _FakeRect_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePathfindingResult_7 extends _i1.SmartFake
    implements _i6.PathfindingResult {
  _FakePathfindingResult_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWireNetwork_8 extends _i1.SmartFake implements _i7.WireNetwork {
  _FakeWireNetwork_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [Ref].
///
/// See the documentation for Mockito's code generation for more information.
class MockRef<State extends Object?> extends _i1.Mock
    implements _i2.Ref<State> {
  MockRef() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ProviderContainer get container => (super.noSuchMethod(
        Invocation.getter(#container),
        returnValue: _FakeProviderContainer_0(
          this,
          Invocation.getter(#container),
        ),
      ) as _i2.ProviderContainer);

  @override
  T refresh<T>(_i2.Refreshable<T>? provider) => (super.noSuchMethod(
        Invocation.method(
          #refresh,
          [provider],
        ),
        returnValue: _i8.dummyValue<T>(
          this,
          Invocation.method(
            #refresh,
            [provider],
          ),
        ),
      ) as T);

  @override
  void invalidate(_i2.ProviderOrFamily? provider) => super.noSuchMethod(
        Invocation.method(
          #invalidate,
          [provider],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void listenSelf(
    void Function(
      State?,
      State,
    )? listener, {
    void Function(
      Object,
      StackTrace,
    )? onError,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #listenSelf,
          [listener],
          {#onError: onError},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void invalidateSelf() => super.noSuchMethod(
        Invocation.method(
          #invalidateSelf,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onAddListener(void Function()? cb) => super.noSuchMethod(
        Invocation.method(
          #onAddListener,
          [cb],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onRemoveListener(void Function()? cb) => super.noSuchMethod(
        Invocation.method(
          #onRemoveListener,
          [cb],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onResume(void Function()? cb) => super.noSuchMethod(
        Invocation.method(
          #onResume,
          [cb],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onCancel(void Function()? cb) => super.noSuchMethod(
        Invocation.method(
          #onCancel,
          [cb],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onDispose(void Function()? cb) => super.noSuchMethod(
        Invocation.method(
          #onDispose,
          [cb],
        ),
        returnValueForMissingStub: null,
      );

  @override
  T read<T>(_i2.ProviderListenable<T>? provider) => (super.noSuchMethod(
        Invocation.method(
          #read,
          [provider],
        ),
        returnValue: _i8.dummyValue<T>(
          this,
          Invocation.method(
            #read,
            [provider],
          ),
        ),
      ) as T);

  @override
  bool exists(_i2.ProviderBase<Object?>? provider) => (super.noSuchMethod(
        Invocation.method(
          #exists,
          [provider],
        ),
        returnValue: false,
      ) as bool);

  @override
  T watch<T>(_i2.ProviderListenable<T>? provider) => (super.noSuchMethod(
        Invocation.method(
          #watch,
          [provider],
        ),
        returnValue: _i8.dummyValue<T>(
          this,
          Invocation.method(
            #watch,
            [provider],
          ),
        ),
      ) as T);

  @override
  _i2.KeepAliveLink keepAlive() => (super.noSuchMethod(
        Invocation.method(
          #keepAlive,
          [],
        ),
        returnValue: _FakeKeepAliveLink_1(
          this,
          Invocation.method(
            #keepAlive,
            [],
          ),
        ),
      ) as _i2.KeepAliveLink);

  @override
  _i2.ProviderSubscription<T> listen<T>(
    _i2.ProviderListenable<T>? provider,
    void Function(
      T?,
      T,
    )? listener, {
    void Function(
      Object,
      StackTrace,
    )? onError,
    bool? fireImmediately,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #listen,
          [
            provider,
            listener,
          ],
          {
            #onError: onError,
            #fireImmediately: fireImmediately,
          },
        ),
        returnValue: _FakeProviderSubscription_2<T>(
          this,
          Invocation.method(
            #listen,
            [
              provider,
              listener,
            ],
            {
              #onError: onError,
              #fireImmediately: fireImmediately,
            },
          ),
        ),
      ) as _i2.ProviderSubscription<T>);
}

/// A class which mocks [CoordinateSystemService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCoordinateSystemService extends _i1.Mock
    implements _i4.CoordinateSystemService {
  MockCoordinateSystemService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Offset globalToLocal(
    _i3.Offset? globalPosition, {
    _i9.RenderBox? renderBox,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #globalToLocal,
          [globalPosition],
          {#renderBox: renderBox},
        ),
        returnValue: _FakeOffset_3(
          this,
          Invocation.method(
            #globalToLocal,
            [globalPosition],
            {#renderBox: renderBox},
          ),
        ),
      ) as _i3.Offset);

  @override
  _i3.Offset localToGrid(
    _i3.Offset? localPosition,
    _i4.CoordinateContext? context,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #localToGrid,
          [
            localPosition,
            context,
          ],
        ),
        returnValue: _FakeOffset_3(
          this,
          Invocation.method(
            #localToGrid,
            [
              localPosition,
              context,
            ],
          ),
        ),
      ) as _i3.Offset);

  @override
  _i3.Offset gridToLocal(
    _i4.GridPosition? gridPosition,
    _i4.CoordinateContext? context,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #gridToLocal,
          [
            gridPosition,
            context,
          ],
        ),
        returnValue: _FakeOffset_3(
          this,
          Invocation.method(
            #gridToLocal,
            [
              gridPosition,
              context,
            ],
          ),
        ),
      ) as _i3.Offset);

  @override
  _i3.Offset gridToLocalFromOffset(
    _i3.Offset? gridOffset,
    _i4.CoordinateContext? context,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #gridToLocalFromOffset,
          [
            gridOffset,
            context,
          ],
        ),
        returnValue: _FakeOffset_3(
          this,
          Invocation.method(
            #gridToLocalFromOffset,
            [
              gridOffset,
              context,
            ],
          ),
        ),
      ) as _i3.Offset);

  @override
  _i4.GridPosition? localToGridPosition(
    _i3.Offset? localPosition,
    _i4.CoordinateContext? context,
  ) =>
      (super.noSuchMethod(Invocation.method(
        #localToGridPosition,
        [
          localPosition,
          context,
        ],
      )) as _i4.GridPosition?);

  @override
  _i4.GridPosition? screenToGrid(
    _i3.Offset? screenPosition,
    _i4.CoordinateContext? context, {
    _i9.RenderBox? renderBox,
  }) =>
      (super.noSuchMethod(Invocation.method(
        #screenToGrid,
        [
          screenPosition,
          context,
        ],
        {#renderBox: renderBox},
      )) as _i4.GridPosition?);

  @override
  _i4.CoordinateValidationResult validateDropPosition(
    _i3.Offset? screenPosition,
    _i4.CoordinateContext? context, {
    _i9.RenderBox? renderBox,
    Set<_i4.GridPosition>? occupiedPositions,
    bool? requireEmptyCell = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #validateDropPosition,
          [
            screenPosition,
            context,
          ],
          {
            #renderBox: renderBox,
            #occupiedPositions: occupiedPositions,
            #requireEmptyCell: requireEmptyCell,
          },
        ),
        returnValue: _FakeCoordinateValidationResult_4(
          this,
          Invocation.method(
            #validateDropPosition,
            [
              screenPosition,
              context,
            ],
            {
              #renderBox: renderBox,
              #occupiedPositions: occupiedPositions,
              #requireEmptyCell: requireEmptyCell,
            },
          ),
        ),
      ) as _i4.CoordinateValidationResult);

  @override
  _i4.GridPosition? getSnappedValidPosition(
    _i3.Offset? screenPosition,
    _i4.CoordinateContext? context, {
    _i9.RenderBox? renderBox,
    Set<_i4.GridPosition>? occupiedPositions,
    bool? requireEmptyCell = true,
  }) =>
      (super.noSuchMethod(Invocation.method(
        #getSnappedValidPosition,
        [
          screenPosition,
          context,
        ],
        {
          #renderBox: renderBox,
          #occupiedPositions: occupiedPositions,
          #requireEmptyCell: requireEmptyCell,
        },
      )) as _i4.GridPosition?);

  @override
  void clearCache() => super.noSuchMethod(
        Invocation.method(
          #clearCache,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ViewportService].
///
/// See the documentation for Mockito's code generation for more information.
class MockViewportService extends _i1.Mock implements _i5.ViewportService {
  MockViewportService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set onError(_i10.ErrorListener? _onError) => super.noSuchMethod(
        Invocation.setter(
          #onError,
          _onError,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get mounted => (super.noSuchMethod(
        Invocation.getter(#mounted),
        returnValue: false,
      ) as bool);

  @override
  _i11.Stream<_i5.ViewportState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i11.Stream<_i5.ViewportState>.empty(),
      ) as _i11.Stream<_i5.ViewportState>);

  @override
  _i5.ViewportState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeViewportState_5(
          this,
          Invocation.getter(#state),
        ),
      ) as _i5.ViewportState);

  @override
  set state(_i5.ViewportState? value) => super.noSuchMethod(
        Invocation.setter(
          #state,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.ViewportState get debugState => (super.noSuchMethod(
        Invocation.getter(#debugState),
        returnValue: _FakeViewportState_5(
          this,
          Invocation.getter(#debugState),
        ),
      ) as _i5.ViewportState);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  void updateScale(double? newScale) => super.noSuchMethod(
        Invocation.method(
          #updateScale,
          [newScale],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updatePan(_i3.Offset? delta) => super.noSuchMethod(
        Invocation.method(
          #updatePan,
          [delta],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setCanvasSize(_i3.Size? size) => super.noSuchMethod(
        Invocation.method(
          #setCanvasSize,
          [size],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void reset() => super.noSuchMethod(
        Invocation.method(
          #reset,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Rect getVisibleGridBounds() => (super.noSuchMethod(
        Invocation.method(
          #getVisibleGridBounds,
          [],
        ),
        returnValue: _FakeRect_6(
          this,
          Invocation.method(
            #getVisibleGridBounds,
            [],
          ),
        ),
      ) as _i3.Rect);

  @override
  bool updateShouldNotify(
    _i5.ViewportState? old,
    _i5.ViewportState? current,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateShouldNotify,
          [
            old,
            current,
          ],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i10.RemoveListener addListener(
    _i10.Listener<_i5.ViewportState>? listener, {
    bool? fireImmediately = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
          {#fireImmediately: fireImmediately},
        ),
        returnValue: () {},
      ) as _i10.RemoveListener);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [PathfindingService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPathfindingService extends _i1.Mock
    implements _i6.PathfindingService {
  MockPathfindingService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get levelId => (super.noSuchMethod(
        Invocation.getter(#levelId),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.getter(#levelId),
        ),
      ) as String);

  @override
  _i11.Future<_i6.PathfindingResult> findPath(
    _i4.GridPosition? start,
    _i4.GridPosition? end, {
    _i6.PathfindingAlgorithm? algorithm = _i6.PathfindingAlgorithm.astar,
    Set<_i4.GridPosition>? occupiedPositions,
    int? maxNodes = 1000,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #findPath,
          [
            start,
            end,
          ],
          {
            #algorithm: algorithm,
            #occupiedPositions: occupiedPositions,
            #maxNodes: maxNodes,
          },
        ),
        returnValue:
            _i11.Future<_i6.PathfindingResult>.value(_FakePathfindingResult_7(
          this,
          Invocation.method(
            #findPath,
            [
              start,
              end,
            ],
            {
              #algorithm: algorithm,
              #occupiedPositions: occupiedPositions,
              #maxNodes: maxNodes,
            },
          ),
        )),
      ) as _i11.Future<_i6.PathfindingResult>);

  @override
  void clearCaches() => super.noSuchMethod(
        Invocation.method(
          #clearCaches,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  Map<String, dynamic> getStatistics() => (super.noSuchMethod(
        Invocation.method(
          #getStatistics,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);
}

/// A class which mocks [WireNetworkService].
///
/// See the documentation for Mockito's code generation for more information.
class MockWireNetworkService extends _i1.Mock
    implements _i7.WireNetworkService {
  MockWireNetworkService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get levelId => (super.noSuchMethod(
        Invocation.getter(#levelId),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.getter(#levelId),
        ),
      ) as String);

  @override
  _i11.Future<_i7.WireNetwork> createNetworkFromPath(
    _i12.ComponentPort? startPort,
    _i12.ComponentPort? endPort,
    List<_i4.GridPosition>? path,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createNetworkFromPath,
          [
            startPort,
            endPort,
            path,
          ],
        ),
        returnValue: _i11.Future<_i7.WireNetwork>.value(_FakeWireNetwork_8(
          this,
          Invocation.method(
            #createNetworkFromPath,
            [
              startPort,
              endPort,
              path,
            ],
          ),
        )),
      ) as _i11.Future<_i7.WireNetwork>);

  @override
  List<_i7.WireNetwork> getAllNetworks() => (super.noSuchMethod(
        Invocation.method(
          #getAllNetworks,
          [],
        ),
        returnValue: <_i7.WireNetwork>[],
      ) as List<_i7.WireNetwork>);

  @override
  _i7.WireNetwork? getNetwork(String? networkId) =>
      (super.noSuchMethod(Invocation.method(
        #getNetwork,
        [networkId],
      )) as _i7.WireNetwork?);

  @override
  List<_i7.WireNetwork> getNetworksAtPosition(_i4.GridPosition? position) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNetworksAtPosition,
          [position],
        ),
        returnValue: <_i7.WireNetwork>[],
      ) as List<_i7.WireNetwork>);

  @override
  _i7.WireJunction? getJunctionAtPosition(_i4.GridPosition? position) =>
      (super.noSuchMethod(Invocation.method(
        #getJunctionAtPosition,
        [position],
      )) as _i7.WireJunction?);

  @override
  void removeNetwork(String? networkId) => super.noSuchMethod(
        Invocation.method(
          #removeNetwork,
          [networkId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  Map<String, dynamic> getStatistics() => (super.noSuchMethod(
        Invocation.method(
          #getStatistics,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  void clear() => super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
