// Mocks generated by Mockito 5.4.5 from annotations
// in sparkcircuit/test/unit/create_component_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i9;

import 'package:flutter_riverpod/flutter_riverpod.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sparkcircuit/application/grid_notifier.dart' as _i3;
import 'package:sparkcircuit/application/notifier_context.dart' as _i7;
import 'package:sparkcircuit/application/transaction.dart' as _i8;
import 'package:sparkcircuit/domain/entities/entities.dart' as _i2;
import 'package:state_notifier/state_notifier.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGrid_0 extends _i1.SmartFake implements _i2.Grid {
  _FakeGrid_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GridNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockGridNotifier extends _i1.Mock implements _i3.GridNotifier {
  MockGridNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Grid get current => (super.noSuchMethod(
        Invocation.getter(#current),
        returnValue: _FakeGrid_0(
          this,
          Invocation.getter(#current),
        ),
      ) as _i2.Grid);

  @override
  List<_i2.ComponentModel> get componentsList => (super.noSuchMethod(
        Invocation.getter(#componentsList),
        returnValue: <_i2.ComponentModel>[],
      ) as List<_i2.ComponentModel>);

  @override
  set onError(_i4.ErrorListener? _onError) => super.noSuchMethod(
        Invocation.setter(
          #onError,
          _onError,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get mounted => (super.noSuchMethod(
        Invocation.getter(#mounted),
        returnValue: false,
      ) as bool);

  @override
  _i5.Stream<_i2.Grid> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i5.Stream<_i2.Grid>.empty(),
      ) as _i5.Stream<_i2.Grid>);

  @override
  _i2.Grid get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeGrid_0(
          this,
          Invocation.getter(#state),
        ),
      ) as _i2.Grid);

  @override
  set state(_i2.Grid? value) => super.noSuchMethod(
        Invocation.setter(
          #state,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.Grid get debugState => (super.noSuchMethod(
        Invocation.getter(#debugState),
        returnValue: _FakeGrid_0(
          this,
          Invocation.getter(#debugState),
        ),
      ) as _i2.Grid);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  void setState(_i2.Grid? newGrid) => super.noSuchMethod(
        Invocation.method(
          #setState,
          [newGrid],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateComponent(_i2.ComponentModel? component) => super.noSuchMethod(
        Invocation.method(
          #updateComponent,
          [component],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addComponent(_i2.ComponentModel? component) => super.noSuchMethod(
        Invocation.method(
          #addComponent,
          [component],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeComponent(String? componentId) => super.noSuchMethod(
        Invocation.method(
          #removeComponent,
          [componentId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearComponents() => super.noSuchMethod(
        Invocation.method(
          #clearComponents,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.ComponentModel? getComponentById(String? id) =>
      (super.noSuchMethod(Invocation.method(
        #getComponentById,
        [id],
      )) as _i2.ComponentModel?);

  @override
  List<_i2.ComponentModel> getComponentsByType(_i2.ComponentType? type) =>
      (super.noSuchMethod(
        Invocation.method(
          #getComponentsByType,
          [type],
        ),
        returnValue: <_i2.ComponentModel>[],
      ) as List<_i2.ComponentModel>);

  @override
  bool updateShouldNotify(
    _i2.Grid? old,
    _i2.Grid? current,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateShouldNotify,
          [
            old,
            current,
          ],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i4.RemoveListener addListener(
    _i6.Listener<_i2.Grid>? listener, {
    bool? fireImmediately = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
          {#fireImmediately: fireImmediately},
        ),
        returnValue: () {},
      ) as _i4.RemoveListener);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [NotifierContext].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotifierContext extends _i1.Mock implements _i7.NotifierContext {
  MockNotifierContext() {
    _i1.throwOnMissingStub(this);
  }
}

/// A class which mocks [GameTransaction].
///
/// See the documentation for Mockito's code generation for more information.
class MockGameTransaction extends _i1.Mock implements _i8.GameTransaction {
  MockGameTransaction() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isCommitted => (super.noSuchMethod(
        Invocation.getter(#isCommitted),
        returnValue: false,
      ) as bool);

  @override
  bool get isRolledBack => (super.noSuchMethod(
        Invocation.getter(#isRolledBack),
        returnValue: false,
      ) as bool);

  @override
  bool get isActive => (super.noSuchMethod(
        Invocation.getter(#isActive),
        returnValue: false,
      ) as bool);

  @override
  void onCommit(_i5.Future<void> Function()? handler) => super.noSuchMethod(
        Invocation.method(
          #onCommit,
          [handler],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onPostCommit(_i9.VoidCallback? callback) => super.noSuchMethod(
        Invocation.method(
          #onPostCommit,
          [callback],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onRollback(_i9.VoidCallback? handler) => super.noSuchMethod(
        Invocation.method(
          #onRollback,
          [handler],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> commit() => (super.noSuchMethod(
        Invocation.method(
          #commit,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void rollback() => super.noSuchMethod(
        Invocation.method(
          #rollback,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
